{
 "title": "Check-URL (Blackbox Exporter Overview - 5345)",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "targets",
    "query": "label_values(probe_success,target)"
   }
  ]
 },
 "panels": [
  { "title": "$targets UP/DOWN Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "targets" },
  {
   "title": "$targets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{target=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{target=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "SSL Cert Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{target=~\"$targets\"}-time()"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target=~\"$targets\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target=~\"$targets\"})"
    }
   ]
  },
  { "title": "$targets UP/DOWN Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "$targets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{target=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{target=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "SSL Cert Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 16 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{target=~\"$targets\"}-time()"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 20 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target=~\"$targets\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 20 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target=~\"$targets\"})"
    }
   ]
  },
  { "title": "$targets UP/DOWN Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "$targets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{target=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{target=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "SSL Cert Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 27 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{target=~\"$targets\"}-time()"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 31 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target=~\"$targets\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 31 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target=~\"$targets\"})"
    }
   ]
  },
  { "title": "$targets UP/DOWN Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "$targets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{target=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{target=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "SSL Cert Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 38 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{target=~\"$targets\"}-time()"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 42 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target=~\"$targets\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 42 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target=~\"$targets\"})"
    }
   ]
  },
  { "title": "$targets UP/DOWN Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "$targets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 45 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{target=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{target=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "SSL Cert Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 49 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{target=~\"$targets\"}-time()"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 51 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 53 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target=~\"$targets\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 53 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target=~\"$targets\"})"
    }
   ]
  },
  { "title": "$targets UP/DOWN Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "$targets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 56 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{target=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{target=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "SSL Cert Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 60 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{target=~\"$targets\"}-time()"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 62 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 64 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target=~\"$targets\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 64 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target=~\"$targets\"})"
    }
   ]
  },
  { "title": "$targets UP/DOWN Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "$targets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 67 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 69 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 69 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{target=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 69 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{target=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "SSL Cert Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 71 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{target=~\"$targets\"}-time()"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 73 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 75 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target=~\"$targets\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 75 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target=~\"$targets\"})"
    }
   ]
  },
  { "title": "$targets UP/DOWN Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "$targets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 78 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 80 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 80 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{target=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 80 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{target=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "SSL Cert Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 82 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{target=~\"$targets\"}-time()"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 84 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 86 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target=~\"$targets\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 86 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target=~\"$targets\"})"
    }
   ]
  }
 ]
}