{
 "title": "Dashboard List Alerts - 5450",
 "description": "Alerts from prometheus.",
 "tags": [
  "App",
  "Alerts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "15s,1m,5m,1h,6h,1d" },
   { "name": "job", "label": "job", "query": "label_values(ALERTS, job)" },
   {
    "name": "alertname",
    "label": "alertname",
    "query": "label_values(ALERTS, alertname)"
   },
   { "name": "severity", "label": "severity", "query": "label_values(ALERTS,severity)" },
   { "name": "alertstate", "label": "alertstate", "query": "firing,pending" }
  ]
 },
 "panels": [
  {
   "title": "Alerts YELLOW",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",severity=\"YELLOW\"} > 0)  OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Alerts ORANGE",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",severity=\"ORANGE\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Alerts RED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",severity=\"RED\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Numbers Node DOWN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=\"[TOPKID-ALERT]-Instance_Down\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Prometheus Targets",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "count(up)" }
   ]
  },
  {
   "title": "Max Tcp Established",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(node_netstat_Tcp_CurrEstab)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "All Alerts YELLOW Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "severity=\"YELLOW\"",
     "labelSelector": "alertname, instance, description, severity",
     "legendFormat": "{{ summary }}",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "All Alerts ORANGE Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "severity=\"ORANGE\"",
     "labelSelector": "alertname, instance, description, severity",
     "legendFormat": "{{ summary }}",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "All Alerts RED Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "severity=\"RED\"",
     "labelSelector": "alertname, instance, description, severity",
     "legendFormat": "{{ summary }}",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Alerts Graph: FIRING",
   "type": "graph",
   "description": "Alerts Graph: FIRING",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ALERTS{job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",alertstate=~\"firing\"}",
     "legendFormat": "{{instance}}: {{alertname}}"
    }
   ]
  },
  {
   "title": "Alerts Graph: PENDING",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "count(ALERTS{job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",severity=~\"$severity\"})  by (instance,alertname)",
     "legendFormat": "{{instance}} {{alertname}}"
    }
   ]
  }
 ]
}