{
 "title": "Monitor Instance - Only one instance",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance_id",
    "label": "instance_id",
    "query": "label_values(lvirt_domain_info_state, id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instance State",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "lvirt_domain_info_state{id='$instance_id'}",
     "legendFormat": "{{instance}}@{{id}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": " irate(lvirt_domain_info_cpu_time_total{id='$instance_id'}[5m])*100",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Memory Usage ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "(lvirt_domain_mem_in_use_byte{id='$instance_id'}/lvirt_domain_info_memory_available_byte{id='$instance_id'})*100",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": " irate(lvirt_domain_info_cpu_time_total{id='$instance_id'}[5m])*100",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "(lvirt_domain_mem_in_use_byte{id='$instance_id'}/lvirt_domain_info_memory_available_byte{id='$instance_id'})*100",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "iops" }
   ],
   "targets": [
    {
     "expr": "(rate(lvirt_domain_block_stats_read_requests_total{id='$instance_id'}[5m]) + rate(lvirt_domain_block_stats_write_requests_total{id='$instance_id'}[5m]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Read / Write Disk (bps)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Read (-) / Write (+) (bps)" }
   ],
   "targets": [
    {
     "expr": "irate(lvirt_domain_block_stats_write_bytes_total{id='$instance_id'}[1m])",
     "legendFormat": "write - {{device}}"
    },
    {
     "expr": "-irate(lvirt_domain_block_stats_read_bytes_total{id='$instance_id'}[1m])",
     "legendFormat": "read - {{device}}"
    }
   ]
  },
  {
   "title": "Network traffic basic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Packets out (-) / in (+) (bps)" }
   ],
   "targets": [
    {
     "expr": "rate(lvirt_domain_interface_stats_receive_bytes_total{id='$instance_id'}[1m])*8",
     "legendFormat": "recv - {{interface}}"
    },
    {
     "expr": "-rate(lvirt_domain_interface_stats_transmit_bytes_total{id='$instance_id'}[1m])*8",
     "legendFormat": "trans - {{interface}}"
    }
   ]
  }
 ]
}