{
 "title": "Monitor Instance",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "compute_node",
    "label": "compute_node",
    "query": "label_values(up{job=\"libvirt_exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number instances running on this node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(lvirt_domain_info_state{instance=\"$compute_node\"}==1) by (instance)"
    }
   ]
  },
  {
   "title": "Instance State",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "lvirt_domain_info_state{instance=\"$compute_node\"}",
     "legendFormat": "{{instance}}@{{name}}"
    }
   ]
  },
  {
   "title": "Total instances running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(lvirt_domain_info_state==1)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(lvirt_domain_mem_in_use_byte{instance=\"$compute_node\"}/lvirt_domain_info_memory_available_byte{instance=\"$compute_node\"})*100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " irate(lvirt_domain_info_cpu_time_total{instance=\"$compute_node\"}[5m])*100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage Percent",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(lvirt_domain_mem_in_use_byte{instance=\"$compute_node\"}/lvirt_domain_info_memory_available_byte{instance=\"$compute_node\"})*100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage Percent",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": " irate(lvirt_domain_info_cpu_time_total{instance=\"$compute_node\"}[5m])*100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network traffic basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(lvirt_domain_interface_stats_receive_bytes_total{instance=\"$compute_node\"}[5m])",
     "legendFormat": "recv - {{name}}@{{interface}}"
    },
    {
     "expr": "-rate(lvirt_domain_interface_stats_transmit_bytes_total{instance=\"$compute_node\"}[5m])",
     "legendFormat": "trans - {{name}}@{{interface}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(lvirt_domain_block_stats_read_requests_total{instance=\"$compute_node\"}[5m]) + rate(lvirt_domain_block_stats_write_requests_total{instance=\"$compute_node\"}[5m]))",
     "legendFormat": "{{name}}:{{device}}"
    }
   ]
  },
  {
   "title": "Read / Write block per 1m",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(lvirt_domain_block_stats_write_bytes_total{instance=\"$compute_node\"}[1m])",
     "legendFormat": "write - {{name}}@{{device}}"
    },
    {
     "expr": "-irate(lvirt_domain_block_stats_read_bytes_total{instance=\"$compute_node\"}[1m])",
     "legendFormat": "read - {{name}}@{{device}}"
    }
   ]
  }
 ]
}