{
 "title": "MySQL User Statistics | Percona App Copy",
 "tags": [
  "MySQL",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "These graphs require additional options to be enabled for mysqld_exporter: `-collect.info_schema.userstats=true`\n\nAlso `userstat` should be enabled on MySQL."
  },
  {
   "title": "Top Users by Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "irate(mysql_info_schema_user_statistics_total_connections{instance=\"$host\"}[1m])",
     "legendFormat": "{{ user }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22topk(5%2C%20rate(mysql_info_schema_user_statistics_total_connections%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D))%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-10-6%208%3A19%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Top Users by Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "irate(mysql_info_schema_user_statistics_bytes_sent_total{instance=\"$host\"}[1m])",
     "legendFormat": "{{ user }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22topk(5%2C%20rate(mysql_info_schema_user_statistics_total_connections%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D))%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-10-6%208%3A19%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "User statistics select",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "irate(mysql_info_schema_user_statistics_select_commands_total{instance=\"$host\"}[1m])",
     "legendFormat": "{{ user }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22topk(5%2C%20rate(mysql_info_schema_user_statistics_total_connections%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D))%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-10-6%208%3A19%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Top Users by Rows Updated",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "irate(mysql_info_schema_user_statistics_rows_updated_total{instance=\"$host\"}[1m])",
     "legendFormat": "{{ user }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22topk(5%2C%20rate(mysql_info_schema_user_statistics_total_connections%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D))%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-10-6%208%3A19%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Top Users by Busy Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "irate(mysql_info_schema_user_statistics_busy_seconds_total{instance=\"$host\"}[1m])",
     "legendFormat": "{{ user }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22topk(5%2C%20rate(mysql_info_schema_user_statistics_total_connections%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D))%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-10-6%208%3A19%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Top Users by CPU Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "irate(mysql_info_schema_user_statistics_cpu_time_seconds_total{instance=\"$host\"}[1m])",
     "legendFormat": "{{ user }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22topk(5%2C%20rate(mysql_info_schema_user_statistics_total_connections%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D))%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-10-6%208%3A19%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  }
 ]
}